// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransaction = "transactions"

// Transaction mapped from table <transactions>
type Transaction struct {
	ID         int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CampaignID *int32     `gorm:"column:campaign_id" json:"campaign_id"`
	UserID     *int32     `gorm:"column:user_id" json:"user_id"`
	Amount     *int32     `gorm:"column:amount" json:"amount"`
	Status     *string    `gorm:"column:status" json:"status"`
	Code       *string    `gorm:"column:code" json:"code"`
	CreatedAt  *time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt  *time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Transaction's table name
func (*Transaction) TableName() string {
	return TableNameTransaction
}
