version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: bwa
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:7.2.4-alpine
    ports:
      - 6379:6379