version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}

  redis:
    image: redis:7.2.4-alpine
    ports:
      - 6379:6379